[build]
  command = "pnpm run build"
  publish = ".next"

[build.environment]
  # NextAuth.js Configuration
  NEXTAUTH_URL = "https://liftout.netlify.app"
  NEXTAUTH_SECRET = "secure-production-secret-key-for-liftout-platform-2024"
  AUTH_TRUST_HOST = "true"
  
  # API Configuration
  NEXT_PUBLIC_API_URL = "https://liftout.netlify.app/api"
  
  # Node.js Configuration
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[functions]
  # Increase function timeout for larger pages
  timeout = 30

# Redirect rules
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/___netlify-handler"
  status = 200

[[redirects]]
  from = "/_next/static/*"
  to = "/static/:splat"
  status = 200

# Catch-all redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"