[build]
  command = "cd ../.. && mv package.json package.json.bak && mv pnpm-workspace.yaml pnpm-workspace.yaml.bak && mv pnpm-lock.yaml pnpm-lock.yaml.bak 2>/dev/null || true && cd apps/web-app && npm install && npm run build && cd ../.. && mv package.json.bak package.json && mv pnpm-workspace.yaml.bak pnpm-workspace.yaml && mv pnpm-lock.yaml.bak pnpm-lock.yaml 2>/dev/null || true"
  publish = ".next"
  node_version = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"