[build]
  command = "corepack enable pnpm && pnpm --dir ../.. install --frozen-lockfile && pnpm --dir ../.. --filter @liftout/web-app... build"
  publish = ".next"
  node_version = "20"

[[plugins]]
  package = "@netlify/plugin-nextjs"
